### ISSUE TITLE
gaps at pvoutput

### ISSUE THREAD

**Issue by ringlord** [mark0100/omniklogger#3] opened 2022-06-25 05:44 UTC
This is maybe not a software issue of omniklogger, but I would like to ask the question.

The logger is working very well but some data do not show up at the pvoutput site.

For example
```
2022-06-23 19:36:52,146 sid=37533&d=20220623&t=19%3A36&v1=15890.0&v2=4
2022-06-23 19:42:18,164 sid=37533&d=20220623&t=19%3A42&v1=15930.0&v2=3
2022-06-23 19:47:44,182 sid=37533&d=20220623&t=19%3A47&v1=15960.0&v2=2
2022-06-23 19:53:10,200 sid=37533&d=20220623&t=19%3A53&v1=15980.0&v2=2
2022-06-23 19:57:07,864 sid=37533&d=20220623&t=19%3A57&v1=16000.0&v2=2
2022-06-23 20:02:34,883 sid=37533&d=20220623&t=20%3A02&v1=16020.0&v2=2
2022-06-23 20:08:01,902 sid=37533&d=20220623&t=20%3A08&v1=16040.0&v2=1
```

Allthough I got a status 200, the data of 19:53 does not show
`2022-06-23 19:53:10,607 DEBUG PVoutputOutput: response from PVOutput site: b’OK 200: Added Status’`

![image](https://user-images.githubusercontent.com/639884/175760016-4ea13a8f-9183-43d7-8db2-1e1bd7702cd4.png)

Could the reason for that be that the time is too far from 19:50 ?
I have no way of checking  if the time of my WiFi module is correct, maybe that is the reason?

**Comment by mark0100** [comment] 2022-06-25 09:58
Hi Ringlord,

Yes you are right, with 5 minutes intervals on PVOutput sometimes you miss an interval. I have the same problem with my installation.

This behaviour is caused by the effect that omniklogger is a UDP listener and is activated every time a UDP message is received from the inverter. The UDP messages are not received exactly on 5 minute intervals (as shown in your logging).
PVOutput will round up or down to exact 5 minute intervals when accepting data, depending on the exact time the data is received. 
Due to the combination of the above some data is discarded because it is already present as far as PVOutput is concerned. So it will show up as a missing timeslot in PVOutput. 

I have thought about a solution for this problem but to fix it the right way would mean that omniklogger would become much more complex than it is now. I.e. it needs to become a multithreaded application; one thread for receiving the UDP messages from the inverter, and another thread for sending the data to PVOutput in a timely manner.

The missing timeslots on PVOutput are not a big problem for me because 5 minute intervals is already very detailed and the data shown is still correct.
Is it a big problem for you?

**Comment by ringlord** [comment] 2022-06-25 10:34
It is not a big problem. I am glad I am not the only one.

I don't know if it would work, but rounding down the time could maybe fix it as well.
I mean change the time in the http call itself :
instead of 
`2022-06-23 19:53:10,200 sid=37533&d=20220623&t=19%3A53&v1=15980.0&v2=2`
send
`2022-06-23 19:53:10,200 sid=37533&d=20220623&t=19%3A50&v1=15980.0&v2=2`

**Comment by mark0100** [comment] 2022-06-25 17:22
Hi Ringlord,

I think i already thought of this when i first encountered the problem but i'm not sure any more. It was a while back.

With the data in your example above rounding down to the last 5 minute interval should work but i'm not sure it would work with all possible dataflows.
Would it? I have to think about it.

**Comment by ringlord** [comment] 2022-06-26 06:26
5 min 26 sec
5 min 26 sec
3 min 57 sec
5 min 27 sec
5 min 27 sec
If I calculate the time difference between the timestamps, it is mostly 5 minutes 27 seconds.
So that means the time shifts towards the next 5 minute mark.
I think that is causing the gaps.
As long as we don't create duplicates by rounding down, we should be fine.

**Comment by mark0100** [comment] 2022-06-26 08:32
Yes the 'extra' 27 seconds delay every time a message is received will add up until a 5 minute border is crossed and a timeslot is 'skipped'. 

But rounding down in the omniklogger code to the last 5 minute timeslot would not solve the problem then, because that does not make the 27 seconds increment with every received message go away. Correct?

**Comment by ringlord** [comment] 2022-06-26 08:52
8:00:01
8:05:28
8:10:55
8:16:22
8:21:49
8:27:16
8:32:43
8:38:10
8:43:37
8:49:04
8:54:31
8:59:58
9:05:25

You are right, I made a random list in Excel and pretty soon we can see that the 8:59 would round down to 8:55 but the next time 09:05:25 would round to 09:05, creating a gap at 09:00
So yes that would not 'fix' things.
I guess I can live with the situation because for the rest it is pretty stable.
Again thanks for your help.

**Comment by mark0100** [comment] 2022-06-26 09:53
Well i guess this problem comes with the choice for listening to UDP messages from the inverter.

I don't see a fix for this otherwise than switching to TCP and polling the inverter in a timely manner. But then, there are many other projects on Github taking this approach and omniklogger would not offer a significant advantage over all the other projects if it would go that route.

Thank you for straitening out my thought process on the issue Ringlord.

**Closed as completed by mark0100** 2022-06-26 09:53 UTC
